packages:
  - packages/*
  - examples/*

catalog:
  '@biomejs/biome': 1.9.4
  '@changesets/cli': ^2.27.12
  '@types/node': ^20.12.11
  koffi: ^2.15.1
  rimraf: ^5.0.5
  tsx: ^4.19.2
  typescript: ~5.4.5

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@biomejs/biome'
  - koffi
