import * as koffi from 'koffi'
import {
  FFI_ARC_HANDLE,
  FFI_CALLBACK_ID,
  FFI_ERROR_CODE,
  FFI_INT8,
  FFI_INT32,
  FFI_INT64,
  FFI_STRING,
  FFI_USIZE,
  FFI_VOID,
} from './primitives'
import { FfiHandleListStruct } from './structures'

export const FFI_CALLBACK_NO_RESULT = koffi.proto('cb_no_result', FFI_VOID, [FFI_CALLBACK_ID, FFI_ERROR_CODE])
export const FFI_CALLBACK_HANDLE_LIST = koffi.proto('cb_handle_list', FFI_VOID, [
  FFI_CALLBACK_ID,
  FFI_ERROR_CODE,
  FfiHandleListStruct,
])

export const FFI_CALLBACK_INT64 = koffi.proto('cb_int64', FFI_VOID, [FFI_CALLBACK_ID, FFI_ERROR_CODE, FFI_INT64])
export const FFI_CALLBACK_INT8 = koffi.proto('cb_int8', FFI_VOID, [FFI_CALLBACK_ID, FFI_ERROR_CODE, FFI_INT8])
export const FFI_CALLBACK_STRING = koffi.proto('cb_string', FFI_VOID, [FFI_CALLBACK_ID, FFI_ERROR_CODE, FFI_STRING])
export const FFI_CALLBACK_LOG = koffi.proto('cb_log', FFI_VOID, [
  koffi.pointer(FFI_VOID),
  FFI_INT32,
  FFI_STRING,
  FFI_STRING,
  FFI_STRING,
  FFI_STRING,
  FFI_INT32,
])

const FFI_CALLBACK_USIZE = koffi.proto('cb_usize', FFI_VOID, [FFI_CALLBACK_ID, FFI_ERROR_CODE, FFI_USIZE])
export const FFI_CALLBACK_STORE_HANDLE = FFI_CALLBACK_USIZE
export const FFI_CALLBACK_SCAN_HANDLE = FFI_CALLBACK_USIZE
export const FFI_CALLBACK_SESSION_HANDLE = FFI_CALLBACK_USIZE

const FFI_CALLBACK_ARC_HANDLE = koffi.proto('cb_arc_handle', FFI_VOID, [
  FFI_CALLBACK_ID,
  FFI_ERROR_CODE,
  FFI_ARC_HANDLE,
])
export const FFI_CALLBACK_ENTRY_LIST_HANDLE = FFI_CALLBACK_ARC_HANDLE
export const FFI_CALLBACK_LOCAL_KEY_HANDLE = FFI_CALLBACK_ARC_HANDLE
export const FFI_CALLBACK_KEY_ENTRY_LIST_HANDLE = FFI_CALLBACK_ARC_HANDLE
export const FFI_CALLBACK_STRING_LIST_HANDLE = FFI_CALLBACK_ARC_HANDLE
