name: "Askar Wrapper Javascript"

permissions:
  actions: write
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  continous-integration:
    name: Continous Integration
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.JS 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm style:check 

      - name: Build library
        run: pnpm build

      - name: Check types
        run: pnpm types:check

      - name: Run tests
        run: pnpm test

  continous-deployment:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: ['continous-integration']
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.JS 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Set the NPM config
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Publish
        id: publish
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            echo ${{ inputs.release-type }}
            git config --global user.name "Openwallet Foundation"

            if [[ $(cat lerna.json | grep version | head -1 | grep dev) ]]; then
              pnpm release from-package --no-push --no-private --yes --no-git-tag-version --dist-tag=alpha
            else
              pnpm release from-package --no-push --no-private --yes --no-git-tag-version
            fi
